### PR TITLE
fix JDK11 warning from older OkHttp3, use OkHttp4

### PR DESCRIPTION
**Pull request by jonnyzzz**
update Kotlin to 1.3.61, simplify Gradle script

OkHttp4 is binary compatible to OkHttp3, the update does not require
changing other dependencies and Retrofit

### CODE REVIEW

**Comment by jonnyzzz** [comment]
I've checked it again. 1.8 must be enough. I've updated Gradle script to ensure it (unfortunately, we do not have classVersionChecker at hands)

**Comment by jonnyzzz** [comment]
@chashnikov I've updated dependencies once again. It looks fine now, works with JDK8, uses fresh okhttp4. Could we see if that is ok? Shall we bump the version to 1.10 along the way to indicate a major change?

**Comment by chashnikov** [comment]
@jonnyzzz the latest published version is 1.7.27, so it's already look strange that the current version is 1.9. I would change it back to 1.8 to avoid confusion.

**Comment by jonnyzzz** [comment]
Looks good to me. I thought we did have 1.9 releases. It might still
configure those who used jitpack builds from master (where the version was
1.9), it's probably ok

**Pull request merged**
